import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {APP_NAME, SERVER_URL} from "@/lib/constants";
import {Toaster} from "sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: `${APP_NAME}`,
    description: "Generated by create next app",
    metadataBase: new URL(SERVER_URL)
};

export default function RootLayout({
                                       children,
                                       modal,
                                   }: Readonly<{
    modal: React.ReactNode
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        {children}
        {modal}
        <Toaster richColors position="bottom-right" />
        </body>
        </html>
    );
}
